version: "3.9"

services:
  web:
    build: .
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1299@host.docker.internal:5432/thinkrealty_leads
      REDIS_URL: redis://redis:6379/1

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
